### ISSUE TITLE
option to choose between normal / alpha

### ISSUE THREAD

**Issue by silveltman** [endigma/unocss-preset-radix#18]
I find myself using either the regular OR the alpha palette, not both.

Being able to choose would save css file size + would allow for simple use of colors: just use color7, color12 etc and in 1 toggle switch the whole website from normal to alpha. 

I feel like alpha is best in modern/glassy websites. The regular palette is better for more 'standard' sites

**Comment by endigma** [comment]
I'm not sure that's the intention of the palettes, in the default imports its like blue/blue-dark not distinct alphas. What purpose would excluding them serve except counting kilobytes? the whole color palette from radix is like 138 KB, and a more efficient byte counting feature would probably be to rework it to cull all the unused stuff after instead of making the user manually include specific bits

**Comment by silveltman** [comment]
You're probably right. In my case it would primarily be ease of use, being able to switch all values from regular -> alpha without the need for changing classnames.

I understand that this might be uncommon now though, so I would understand if it's not something that should necessarily be built into this plugin.

**Comment by endigma** [comment]
A lot of this plugin is built up as my company needs it, and I'm hoping to rebuild it in a less hacky way at some point, I'll keep your use case in mind.
